name: Full clean & deploy React App via sshpass

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Setup Node.js e cache npm
      - name: Setup Node.js & Cache npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3) Instala dependências localmente (sem build)
      - name: Install dependencies only
        run: |
          npm ci

      # 4) Instala sshpass e rsync
      - name: Install sshpass and rsync
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync

      # 5) Cria diretório e limpa arquivos antigos, preservando apenas .env
      - name: Create directory and clean remote files (keep .env)
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "mkdir -p /www/wwwroot && \
             mkdir -p /www/wwwroot/VorPlayUI && \
             cd /www/wwwroot/VorPlayUI && \
             echo '--- Diretório atual: \$(pwd) ---' && \
             ls -la || true && \
             echo '--- Limpando arquivos antigos (preservando .env) ---' && \
             find . -mindepth 1 -maxdepth 1 ! -name '.env' -exec rm -rf {} + || true"

      # 6) Copia código fonte para o servidor
      - name: Copy source code to server
        run: |
          # copia todo o código fonte (exceto node_modules e .git)
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
            rsync -avz --exclude 'node_modules' --exclude '.git' --exclude 'dist' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/www/wwwroot/VorPlayUI/

      # 7) Faz build no servidor e inicia com PM2
      - name: Build on server and deploy with PM2
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd /www/wwwroot/VorPlayUI && \
             echo '--- Verificando .env do servidor ---' && \
             cat .env && \
             echo '--- Instalando dependências no servidor ---' && \
             npm ci && \
             echo '--- Fazendo build com .env do servidor ---' && \
             npm run build && \
             echo '--- Configurando permissões ---' && \
             chmod -R 755 . && \
             echo '--- Parando PM2 anterior ---' && \
             pm2 delete VorPlayUI || true && \
             echo '--- Iniciando com PM2 serve ---' && \
             pm2 serve dist 3001 --name VorPlayUI --spa && \
             echo '--- Status do PM2 ---' && \
             pm2 list && \
             echo '--- Testando conexão local ---' && \
             sleep 3 && \
             curl -I http://localhost:3001 || echo '⚠️ Não conseguiu conectar localmente' && \
             echo '--- Verificando se porta está aberta ---' && \
             netstat -tlnp | grep :3001 || echo '⚠️ Porta 3001 não encontrada' && \
             echo '✅ Deploy concluído com sucesso'"
